function create_course_model()
%CREATE_COURSE_MODEL Build a modular MATLAB/Simulink 6-DOF UAV model.
%
% The top level follows the course-design subsystem requirement:
% Guidance -> Navigation -> Position Controller -> Attitude Controller ->
% Control Allocation -> Propulsion Dynamics -> 6DOF Dynamics -> Data Logging.

projectRoot = fileparts(fileparts(mfilename('fullpath')));
modelDir = fullfile(projectRoot, 'model');
if ~exist(modelDir, 'dir')
    mkdir(modelDir);
end

modelName = 'uav_6dof_course';
modelPath = fullfile(modelDir, [modelName '.slx']);

if bdIsLoaded(modelName)
    set_param(modelName, 'Dirty', 'off');
    close_system(modelName, 0);
end
if exist(modelPath, 'file')
    delete(modelPath);
end

new_system(modelName);
open_system(modelName);
set_param(modelName, ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', '0.01', ...
    'StartTime', '0', ...
    'StopTime', '20', ...
    'ReturnWorkspaceOutputs', 'on');

add_block('simulink/Sources/Clock', [modelName '/Clock'], 'Position', [35 55 65 85]);
add_block('simulink/Sources/Constant', [modelName '/ScenarioMode'], ...
    'Value', '1', 'Position', [30 125 75 155]);

add_matlab_function(modelName, 'Guidance', guidance_code(), [130 40 285 165]);
add_block('simulink/Discrete/Unit Delay', [modelName '/Navigation Feedback'], ...
    'InitialCondition', '[0;0;0;0;0;0;0;0;0;0;0;0]', ...
    'SampleTime', '0.01', ...
    'Position', [1420 260 1595 320]);
add_matlab_function(modelName, 'Position Controller', position_controller_code(), [350 45 545 170]);
add_matlab_function(modelName, 'Attitude Controller', attitude_controller_code(), [625 55 820 160]);
add_matlab_function(modelName, 'Control Allocation', allocation_code(), [900 55 1080 160]);
add_matlab_function(modelName, 'Propulsion Dynamics', propulsion_code(), [1160 55 1340 160]);
add_matlab_function(modelName, '6DOF Dynamics', dynamics_code(), [1420 45 1615 175]);

add_ts_sink(modelName, 'log_time', 'sim_time', [130 240 285 270]);
add_ts_sink(modelName, 'log_ref_pos', 'sim_ref_pos', [350 215 510 245]);
add_ts_sink(modelName, 'log_att_ref', 'sim_att_ref', [625 215 785 245]);
add_ts_sink(modelName, 'log_control', 'sim_control', [900 215 1060 245]);
add_ts_sink(modelName, 'log_motor_cmd', 'sim_motor_cmd', [1160 215 1320 245]);
add_ts_sink(modelName, 'log_rotor_speed', 'sim_rotor_speed', [1160 265 1320 295]);
add_ts_sink(modelName, 'log_state', 'sim_state', [1665 70 1825 100]);
add_ts_sink(modelName, 'log_accel', 'sim_accel', [1665 125 1825 155]);

add_line(modelName, 'Clock/1', 'Guidance/1', 'autorouting', 'on');
add_line(modelName, 'ScenarioMode/1', 'Guidance/2', 'autorouting', 'on');
add_line(modelName, 'Clock/1', 'log_time/1', 'autorouting', 'on');

add_line(modelName, 'Guidance/1', 'Position Controller/1', 'autorouting', 'on');
add_line(modelName, 'Guidance/2', 'Position Controller/3', 'autorouting', 'on');
add_line(modelName, 'Navigation Feedback/1', 'Position Controller/2', 'autorouting', 'on');

add_line(modelName, 'Position Controller/1', 'Attitude Controller/1', 'autorouting', 'on');
add_line(modelName, 'Position Controller/2', 'Attitude Controller/2', 'autorouting', 'on');
add_line(modelName, 'Navigation Feedback/1', 'Attitude Controller/3', 'autorouting', 'on');

add_line(modelName, 'Attitude Controller/1', 'Control Allocation/1', 'autorouting', 'on');
add_line(modelName, 'Control Allocation/1', 'Propulsion Dynamics/1', 'autorouting', 'on');

add_line(modelName, 'Propulsion Dynamics/1', '6DOF Dynamics/1', 'autorouting', 'on');
add_line(modelName, 'Position Controller/3', '6DOF Dynamics/2', 'autorouting', 'on');
add_line(modelName, 'Position Controller/2', '6DOF Dynamics/3', 'autorouting', 'on');

add_line(modelName, '6DOF Dynamics/1', 'Navigation Feedback/1', 'autorouting', 'on');

add_line(modelName, 'Position Controller/4', 'log_ref_pos/1', 'autorouting', 'on');
add_line(modelName, 'Position Controller/2', 'log_att_ref/1', 'autorouting', 'on');
add_line(modelName, 'Attitude Controller/1', 'log_control/1', 'autorouting', 'on');
add_line(modelName, 'Control Allocation/1', 'log_motor_cmd/1', 'autorouting', 'on');
add_line(modelName, 'Propulsion Dynamics/1', 'log_rotor_speed/1', 'autorouting', 'on');
add_line(modelName, '6DOF Dynamics/1', 'log_state/1', 'autorouting', 'on');
add_line(modelName, '6DOF Dynamics/2', 'log_accel/1', 'autorouting', 'on');

save_system(modelName, modelPath);
close_system(modelName, 0);
fprintf('Created modular model: %s\n', modelPath);
end

function add_matlab_function(modelName, blockName, code, position)
blockPath = [modelName '/' blockName];
add_block('simulink/User-Defined Functions/MATLAB Function', blockPath, ...
    'Position', position);
rt = sfroot;
chart = rt.find('-isa', 'Stateflow.EMChart', 'Path', blockPath);
chart.Script = char(join(string(code), ''));
end

function add_ts_sink(modelName, blockName, variableName, position)
add_block('simulink/Sinks/To Workspace', [modelName '/' blockName], ...
    'VariableName', variableName, ...
    'SaveFormat', 'Timeseries', ...
    'Position', position);
end

function code = guidance_code()
code = [
"function [ref_traj, ref_yaw] = fcn(t, mode)" newline ...
"% ref_traj = [position; velocity; acceleration]." newline ...
"ref_yaw = 0;" newline ...
"x = 0; y = 0; z = 3; vx = 0; vy = 0; vz = 0; ax = 0; ay = 0; az = 0;" newline ...
"if mode < 1.5" newline ...
"    [z, vz, az] = quintic_segment(t, 0, 5, 0, 3);" newline ...
"elseif mode < 2.5" newline ...
"    [z, vz, az] = quintic_segment(t, 0, 5, 0, 3);" newline ...
"    [x, vx, ax] = quintic_segment(t, 5, 18, 0, 6);" newline ...
"elseif mode < 3.5" newline ...
"    [z, vz, az] = quintic_segment(t, 0, 5, 0, 3);" newline ...
"    [z2, vz2, az2] = quintic_segment(t, 8, 16, 3, 5);" newline ...
"    if t >= 8" newline ...
"        z = z2; vz = vz2; az = az2;" newline ...
"    end" newline ...
"else" newline ...
"    [z, vz, az] = quintic_segment(t, 0, 5, 0, 3);" newline ...
"    [y, vy, ay] = quintic_segment(t, 5, 17, 0, 3);" newline ...
"end" newline ...
"ref_traj = [x; y; z; vx; vy; vz; ax; ay; az];" newline ...
"end" newline ...
"" newline ...
"function [p, v, a] = quintic_segment(t, t0, tf, p0, pf)" newline ...
"if t <= t0" newline ...
"    p = p0; v = 0; a = 0;" newline ...
"elseif t >= tf" newline ...
"    p = pf; v = 0; a = 0;" newline ...
"else" newline ...
"    T = tf - t0;" newline ...
"    s = (t - t0) / T;" newline ...
"    ds = 1 / T;" newline ...
"    h = 10*s^3 - 15*s^4 + 6*s^5;" newline ...
"    hd = (30*s^2 - 60*s^3 + 30*s^4) * ds;" newline ...
"    hdd = (60*s - 180*s^2 + 120*s^3) * ds * ds;" newline ...
"    p = p0 + (pf - p0) * h;" newline ...
"    v = (pf - p0) * hd;" newline ...
"    a = (pf - p0) * hdd;" newline ...
"end" newline ...
"end"];
end

function code = position_controller_code()
code = [
"function [U1_cmd, att_ref, acc_cmd, ref_pos_out] = fcn(ref_traj, nav_state, ref_yaw)" newline ...
"m = 1.2; g = 9.8; dt = 0.01;" newline ...
"persistent integ_pos" newline ...
"if isempty(integ_pos)" newline ...
"    integ_pos = zeros(3,1);" newline ...
"end" newline ...
"pos = nav_state(1:3); vel = nav_state(4:6);" newline ...
"ref_pos = ref_traj(1:3); ref_vel = ref_traj(4:6); ref_acc = ref_traj(7:9);" newline ...
"kp = [0.55; 0.55; 1.80]; ki = [0.00; 0.00; 0.01]; kd = [1.65; 1.65; 2.35];" newline ...
"err = ref_pos - pos;" newline ...
"integ_pos = min(max(integ_pos + err*dt, -2), 2);" newline ...
"vel_err = ref_vel - vel;" newline ...
"acc_cmd = ref_acc + kp.*err + ki.*integ_pos + kd.*vel_err;" newline ...
"acc_cmd(1) = min(max(acc_cmd(1), -0.80), 0.80);" newline ...
"acc_cmd(2) = min(max(acc_cmd(2), -0.80), 0.80);" newline ...
"acc_cmd(3) = min(max(acc_cmd(3), -4.0), 4.0);" newline ...
"yaw = ref_yaw;" newline ...
"phi_ref = (acc_cmd(1)*sin(yaw) - acc_cmd(2)*cos(yaw))/g;" newline ...
"theta_ref = (acc_cmd(1)*cos(yaw) + acc_cmd(2)*sin(yaw))/g;" newline ...
"phi_ref = min(max(phi_ref, -0.12), 0.12);" newline ...
"theta_ref = min(max(theta_ref, -0.12), 0.12);" newline ...
"att_ref = [phi_ref; theta_ref; yaw];" newline ...
"U1_cmd = min(max(m*(g + acc_cmd(3)), 0.2*m*g), 1.8*m*g);" newline ...
"ref_pos_out = ref_pos;" newline ...
"end"];
end

function code = attitude_controller_code()
code = [
"function control = fcn(U1_cmd, att_ref, nav_state)" newline ...
"control = zeros(4,1);" newline ...
"dt = 0.01;" newline ...
"persistent integ_att" newline ...
"if isempty(integ_att)" newline ...
"    integ_att = zeros(3,1);" newline ...
"end" newline ...
"eul = nav_state(7:9); omega = nav_state(10:12);" newline ...
"kp = [6.2; 6.2; 3.2]; ki = [0.0; 0.0; 0.0]; kd = [2.8; 2.8; 1.6];" newline ...
"err = att_ref - eul;" newline ...
"err(3) = atan2(sin(err(3)), cos(err(3)));" newline ...
"integ_att = min(max(integ_att + err*dt, -1), 1);" newline ...
"tau = kp.*err + ki.*integ_att - kd.*omega;" newline ...
"tau = min(max(tau, [-0.8; -0.8; -0.25]), [0.8; 0.8; 0.25]);" newline ...
"control(:) = [U1_cmd; tau];" newline ...
"end"];
end

function code = allocation_code()
code = [
"function motor_cmd = fcn(control)" newline ...
"motor_cmd = zeros(4,1);" newline ...
"kf = 3.1e-5; l = 0.25; km = 1.2e-6;" newline ...
"U1 = control(1); tau = control(2:4);" newline ...
"w2cmd = zeros(4,1);" newline ...
"w2cmd(1) = U1/(4*kf) - tau(2)/(2*kf*l) + tau(3)/(4*km);" newline ...
"w2cmd(2) = U1/(4*kf) + tau(1)/(2*kf*l) - tau(3)/(4*km);" newline ...
"w2cmd(3) = U1/(4*kf) + tau(2)/(2*kf*l) + tau(3)/(4*km);" newline ...
"w2cmd(4) = U1/(4*kf) - tau(1)/(2*kf*l) - tau(3)/(4*km);" newline ...
"w2cmd = min(max(w2cmd, 0), 900^2);" newline ...
"motor_cmd(:) = sqrt(w2cmd);" newline ...
"end"];
end

function code = propulsion_code()
code = [
"function rotor_speed = fcn(motor_cmd)" newline ...
"rotor_speed = zeros(4,1);" newline ...
"persistent w" newline ...
"dt = 0.01; tau = 0.10;" newline ...
"if isempty(w)" newline ...
"    w = zeros(4,1);" newline ...
"end" newline ...
"w = w + dt/tau*(motor_cmd - w);" newline ...
"rotor_speed(:) = w;" newline ...
"end"];
end

function code = dynamics_code()
code = [
"function [state, accel] = fcn(rotor_speed, acc_cmd, att_ref)" newline ...
"% 6DOF rigid-body dynamics driven by rotor thrust and torque." newline ...
"% acc_cmd and att_ref are retained for the subsystem interface/logging chain." newline ...
"persistent x" newline ...
"dt = 0.01; m = 1.2; g = 9.8;" newline ...
"kf = 3.1e-5; l = 0.25; km = 1.2e-6;" newline ...
"I = [0.025; 0.025; 0.045];" newline ...
"lin_drag = [0.10; 0.10; 0.16]; ang_drag = [0.015; 0.015; 0.020];" newline ...
"if isempty(x)" newline ...
"    x = zeros(12,1);" newline ...
"end" newline ...
"pos = x(1:3); vel = x(4:6); eul = x(7:9); omega = x(10:12);" newline ...
"phi = eul(1); theta = eul(2); psi = eul(3);" newline ...
"w2 = rotor_speed(:).*rotor_speed(:);" newline ...
"f = kf*w2;" newline ...
"U1 = sum(f);" newline ...
"tau = [l*kf*(w2(2)-w2(4)); l*kf*(w2(3)-w2(1)); km*(w2(1)-w2(2)+w2(3)-w2(4))];" newline ...
"cphi = cos(phi); sphi = sin(phi); cth = cos(theta); sth = sin(theta); cpsi = cos(psi); spsi = sin(psi);" newline ...
"R = [cpsi*cth, cpsi*sth*sphi-spsi*cphi, cpsi*sth*cphi+spsi*sphi;" newline ...
"     spsi*cth, spsi*sth*sphi+cpsi*cphi, spsi*sth*cphi-cpsi*sphi;" newline ...
"     -sth,     cth*sphi,                    cth*cphi];" newline ...
"thrust_inertial = R*[0;0;U1];" newline ...
"acc = thrust_inertial/m - [0;0;g] - lin_drag.*vel;" newline ...
"gyro = cross(omega, I.*omega);" newline ...
"omega_dot = (tau - gyro - ang_drag.*omega)./I;" newline ...
"cth_safe = sign(cth)*max(abs(cth), 0.05);" newline ...
"eul_dot = [1, sphi*tan(theta), cphi*tan(theta);" newline ...
"           0, cphi,           -sphi;" newline ...
"           0, sphi/cth_safe,   cphi/cth_safe] * omega;" newline ...
"vel = vel + acc*dt;" newline ...
"pos = pos + vel*dt;" newline ...
"omega = omega + omega_dot*dt;" newline ...
"eul = eul + eul_dot*dt;" newline ...
"eul(3) = atan2(sin(eul(3)), cos(eul(3)));" newline ...
"x = [pos; vel; eul; omega];" newline ...
"state = x;" newline ...
"accel = [acc; omega_dot];" newline ...
"end"];
end
