function P = init_uav_params()
%INIT_UAV_PARAMS Parameters used by the course UAV 6-DOF Simulink model.
%
% The Simulink model generated by create_course_model.m uses the same
% numerical values. This file is kept as the single readable parameter table
% for checking, plotting, and documentation.

P.mass = 1.2;                 % kg
P.g = 9.8;                    % m/s^2
P.arm = 0.25;                 % m
P.kf = 3.1e-5;                % N/(rad/s)^2
P.km = 1.2e-6;                % N*m/(rad/s)^2
P.Ix = 0.025;                 % kg*m^2
P.Iy = 0.025;                 % kg*m^2
P.Iz = 0.045;                 % kg*m^2
P.dt = 0.01;                  % s
P.motor_tau = 0.10;           % s
P.max_motor_speed = 900;      % rad/s
P.max_tilt = deg2rad(20);     % rad

P.pos_kp = [0.80; 0.80; 1.40];
P.pos_kd = [1.30; 1.30; 1.90];
P.att_kp = [8.0; 8.0; 4.0];
P.att_kd = [3.0; 3.0; 1.8];

P.linear_drag = [0.10; 0.10; 0.16];
P.angular_drag = [0.015; 0.015; 0.020];

P.hover.ref_pos = [0; 0; 3];
P.hover.ref_yaw = 0;
P.level_flight.cruise_speed = 0.6;
P.level_flight.ref_altitude = 3;
P.level_flight.ref_yaw = 0;
P.level_flight.max_x = 6;
end
